### ISSUE TITLE
[BUG] Armor Workbench

### ISSUE THREAD

**Issue by Xikaro** [brachy84/MechTech#7]
**Describe the bug**
The workbench does not open on the server, an error is displayed in the console

**Versions**
Forge: 14.23.5.2860
GTCEu: 2.4.1-beta
_Modpack:   https://www.curseforge.com/minecraft/modpacks/terrafirmagreg
_Addons: devtech, GCM, GTFO

**Setup**
Multiplayer

**Steps To Reproduce**
1) Put a workbench on the server
2) Tried to open it

**Expected behavior**
Must open

_Please fill in as much useful information as possible. Also please remove all unused sections._
[07:51:16] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_301]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_301]
        at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:910) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[guava-21.0.jar:?]
        at gregtech.api.gui.ModularUI$Builder.<init>(ModularUI.java:188) ~[ModularUI$Builder.class:?]
        at gregtech.api.gui.ModularUI.builder(ModularUI.java:138) ~[ModularUI.class:?]
        at com.brachy84.mechtech.common.machines.MetaTileEntityArmorWorkbench.createUI(MetaTileEntityArmorWorkbench.java:112) ~[MetaTileEntityArmorWorkbench.class:?]
        at gregtech.api.metatileentity.MetaTileEntityUIFactory.createUITemplate(MetaTileEntityUIFactory.java:31) ~[MetaTileEntityUIFactory.class:?]
        at gregtech.api.metatileentity.MetaTileEntityUIFactory.createUITemplate(MetaTileEntityUIFactory.java:18) ~[MetaTileEntityUIFactory.class:?]
        at gregtech.api.gui.UIFactory.openUI(UIFactory.java:36) ~[UIFactory.class:?]
        at gregtech.api.metatileentity.MetaTileEntity.onRightClick(MetaTileEntity.java:400) ~[MetaTileEntity.class:?]
        at gregtech.api.metatileentity.MetaTileEntity.onCoverRightClick(MetaTileEntity.java:373) ~[MetaTileEntity.class:?]
        at gregtech.api.block.machines.BlockMachine.onBlockActivated(BlockMachine.java:338) ~[BlockMachine.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:555) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:1157) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_301]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_301]
        at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
        ... 5 more

**Comment by brachy84** [comment]
Should be fixed
