### ISSUE TITLE
[BUG] Tesla

### ISSUE THREAD

**Issue by Xikaro** [brachy84/MechTech#8]
**Describe the bug**
When collecting tesla, on the server, the server crashes

**Versions**
Forge: 14.23.5.2860
GTCEu: 2.4.1-beta
_Modpack:   https://www.curseforge.com/minecraft/modpacks/terrafirmagreg
_Addons: devtech, GCM, GTFO

**Setup**
Multiplayer

**Steps To Reproduce**
1) assemble a tesla, put a controller
2) Server crash

**Expected behavior**
Should work

Please fill in as much useful information as possible. Also please remove all unused sections.
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Don't be sad, have a hug! <3

Time: 2022-10-04 08:03:36 MSK
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V
    at com.brachy84.mechtech.common.machines.multis.MetaTileEntityTeslaTower.updateWirelessEnergyMode(MetaTileEntityTeslaTower.java:224)
    at com.brachy84.mechtech.common.machines.multis.MetaTileEntityTeslaTower.updateFormedValid(MetaTileEntityTeslaTower.java:104)
    at gregtech.api.metatileentity.multiblock.MultiblockControllerBase.update(MultiblockControllerBase.java:83)
    at gregtech.api.metatileentity.MetaTileEntityHolder.update(MetaTileEntityHolder.java:185)
    at net.minecraft.world.World.updateEntities(World.java:2122)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:742)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:984)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:475)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:834)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
    at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block entity being ticked --
  Name: gregtech:machine // gregtech.api.metatileentity.MetaTileEntityHolder
  Block type: ID #704 (tile.unnamed // gregtech.api.block.machines.BlockMachine // gregtech:machine)
  Block data value: 0 / 0x0 / 0b0000
  Block location: World: (472,168,420), Chunk: (at 8,10,4 in 29,26; contains blocks 464,0,416 to 479,255,431), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Actual block type: ID #704 (tile.unnamed // gregtech.api.block.machines.BlockMachine // gregtech:machine)
  Actual block data value: 0 / 0x0 / 0b0000
  Block Entity NBT: {CustomName:"",x:472,y:168,ForgeCaps:{},MetaTileEntity:{ActiveTimer:0,CachedLightValue:0,VoidingItems:0b,Maintenance:63b,ImportInventory:[],VoidingFluids:0b,DefenseMode:0b,Fragile:0b,Covers:[],FrontFacing:3,ExportFluidInventory:{TankAmount:0,Tanks:[]},Muffled:0b,VoidingMode:0,ExportInventory:[],ImportFluidInventory:{TankAmount:0,Tanks:[]}},z:420,MetaId:"mechtech:tesla_tower",id:"gregtech:machine"}

**Comment by brachy84** [comment]
I have no idea why that happens
